name: Update Dalamud Plugin Repository

on:
  schedule:
    - cron: '0 * * * *' # Run at the start of every hour
  workflow_dispatch: # Allows manual trigger

jobs:
  update-json:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3 # Check out the repository to the runner

    - name: Set up Python
      uses: actions/setup-python@v4 # Set up Python environment
      with:
        python-version: '3.x' # Specify the Python version

    - name: Cache pip
      uses: actions/cache@v3 # Cache pip dependencies to speed up workflow
      with:
        path: ~/.cache/pip # Path to pip cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }} # Unique cache key based on OS and requirements file
        restore-keys: |
          ${{ runner.os }}-pip- # Fallback key

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip # Upgrade pip
        pip install requests # Install required dependencies

    - name: Check for new plugin release and update JSON
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use GitHub token for authentication
      run: python .github/scripts/update_json.py # Run the Python script to update JSON

    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com" # Set Git user email
        git config --local user.name "GitHub Action" # Set Git user name
        git add -A # Stage all changes
        git diff-index --quiet HEAD || git commit -m "Update Dalamud repository JSON" -a # Commit changes if there are any
        git push # Push changes to the repository